import { Campaign } from './types';

export const initialCampaigns: Campaign[] = [
  {
    id: 'camp_1',
    patientName: 'Lucas Silva',
    patientAge: 4,
    patientOrigin: 'Petrolina - PE',
    hospitalName: 'InCor (Instituto do Coração)',
    procedureType: 'Cirurgia Cardíaca Pediátrica',
    procedureDate: '2026-07-02',
    companionName: 'Maria de Lourdes',
    companionRelationship: 'Mãe',
    budgetBreakdown: {
      transport: 1100,
      lodging: 1300,
      food: 600,
      localTransit: 200,
    },
    targetAmount: 3200,
    raisedAmount: 2650,
    story: 'Lucas nasceu com uma cardiopatia congênita complexa e precisa realizar sua segunda cirurgia corretiva em São Paulo. Dona Maria de Lourdes, mãe solo e trabalhadora informal, não tem parentes na capital paulista e precisa de apoio para custear as passagens de ônibus, hospedagem em uma pensão próxima ao hospital e alimentação básica durante as duas semanas previstas de internação de Lucas.',
    status: 'active',
    createdAt: '2026-06-21',
    daysLeft: 3,
    photoUrl: 'https://images.unsplash.com/photo-1536640712-4d4c36ff0e4e?q=80&w=600&auto=format&fit=crop'
  },
  {
    id: 'camp_2',
    patientName: 'Sebastião Souza',
    patientAge: 58,
    patientOrigin: 'Montes Claros - MG',
    hospitalName: 'Hospital das Clínicas da FMUSP',
    procedureType: 'Transplante Renal Correlativo',
    procedureDate: '2026-07-04',
    companionName: 'Clarisse Souza',
    companionRelationship: 'Filha',
    budgetBreakdown: {
      transport: 700,
      lodging: 1200,
      food: 700,
      localTransit: 200,
    },
    targetAmount: 2800,
    raisedAmount: 1450,
    story: 'Após 5 anos enfrentando sessões exaustivas de hemodiálise, o Sr. Sebastião finalmente conseguiu um doador compatível e fará seu transplante de rim. Sua filha Clarisse será sua acompanhante essencial durante o procedimento e recuperação. Os custos de permanência em São Paulo são proibitivos para a família, que vive com um salário mínimo regional.',
    status: 'active',
    createdAt: '2026-06-23',
    daysLeft: 5,
    photoUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=600&auto=format&fit=crop'
  },
  {
    id: 'camp_3',
    patientName: 'Sofia Ramos',
    patientAge: 12,
    patientOrigin: 'Campo Grande - MS',
    hospitalName: 'A.C. Camargo Cancer Center',
    procedureType: 'Neurocirurgia Oncológica',
    procedureDate: '2026-07-06',
    companionName: 'Carlos Ramos',
    companionRelationship: 'Pai',
    budgetBreakdown: {
      transport: 1000,
      lodging: 1500,
      food: 800,
      localTransit: 200,
    },
    targetAmount: 3500,
    raisedAmount: 850,
    story: 'Sofia está lutando bravamente contra um tumor no sistema nervoso central. Ela passará por uma cirurgia de ressecção tumoral de alta complexidade em São Paulo. Seu pai Carlos, pedreiro desempregado, a acompanhará. A família precisa de suporte para transporte rodoviário de ida e volta, hospedagem temporária adaptada às necessidades de Sofia e alimentação para o pai.',
    status: 'active',
    createdAt: '2026-06-24',
    daysLeft: 7,
    photoUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?q=80&w=600&auto=format&fit=crop'
  },
  {
    id: 'camp_4',
    patientName: 'Juliano Rodrigues',
    patientAge: 8,
    patientOrigin: 'Santarém - PA',
    hospitalName: 'Beneficência Portuguesa de São Paulo',
    procedureType: 'Correção de Cardiopatia Congênita',
    procedureDate: '2026-05-15',
    companionName: 'Regina Rodrigues',
    companionRelationship: 'Tia',
    budgetBreakdown: {
      transport: 1100,
      lodging: 1200,
      food: 600,
      localTransit: 200,
    },
    targetAmount: 3100,
    raisedAmount: 3100,
    story: 'Juliano viajou do interior do Pará para operar o coração em São Paulo. Graças à mobilização rápida de 114 doadores nos 7 dias anteriores à sua cirurgia, sua tia Regina pôde se hospedar de forma digna e alimentá-lo com segurança na fase pós-operatória. Juliano teve excelente recuperação e já retornou à sua cidade natal.',
    status: 'completed',
    createdAt: '2026-05-08',
    daysLeft: 0,
    photoUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=600&auto=format&fit=crop',
    thankYouMessage: 'Agradecemos de todo coração a cada pessoa que doou! Sem esse amparo financeiro, eu não teria como permanecer perto do Juliano nesses 15 dias decisivos de internação e repouso. Ver meu sobrinho bem e recuperado sabendo que tínhamos um prato de comida e cama garantidos foi um verdadeiro milagre. Que Deus abençoe a todos!'
  },
  {
    id: 'camp_5',
    patientName: 'Maria Helena Azevedo',
    patientAge: 65,
    patientOrigin: 'Jacobina - BA',
    hospitalName: 'ICESP (Instituto do Câncer de São Paulo)',
    procedureType: 'Cirurgia de Tireoidectomia Total',
    procedureDate: '2026-06-10',
    companionName: 'Vinícius Azevedo',
    companionRelationship: 'Neto',
    budgetBreakdown: {
      transport: 800,
      lodging: 1000,
      food: 600,
      localTransit: 200,
    },
    targetAmount: 2600,
    raisedAmount: 2600,
    story: 'Dona Maria Helena realizou a remoção cirúrgica de um carcinoma na tireoide. Seu neto Vinícius pôde lhe dar toda a assistência de locomoção e cuidados necessários graças ao acolhimento integral financiado pelos doadores da Presença que Cura. A cirurgia foi um sucesso absoluto e ela já iniciou o tratamento complementar em sua cidade.',
    status: 'completed',
    createdAt: '2026-06-03',
    daysLeft: 0,
    photoUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=600&auto=format&fit=crop',
    thankYouMessage: 'Minha avó é meu maior tesouro. Ver a cirurgia dela ser realizada com sucesso, sem o estresse de não sabermos onde iríamos dormir ou se teríamos dinheiro para nos deslocar até o ICESP, foi um alento sem tamanho. Agradeço imensamente à ONG e a todos os doadores por devolverem a saúde da minha avó e a nossa paz de espírito.'
  }
];
